# Source: demo-go-app/templates/demo-app.yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-app-prod
spec:
  replicas: 2
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        role: frontend
        env: prod
    spec:
      containers:
      - name: frontend
        image: harshals/demo-go-app:master.4
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
        ports:
        - name: frontend
          containerPort: 8000
---
# Source: demo-go-app/templates/demo-app.yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-app-canary
spec:
  replicas: 2
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: harshals/demo-go-app:prod.6
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
        ports:
        - name: frontend
          containerPort: 8000
